In [14]:
import numpy as np
import pandas as pd
from Querys.Query_geral import df_query_geral, din_tr, din_vcto_medio
from Querys.Analise_de_compra_por_estoque import df_analise_compra_por_estoque

# Removendo duplicatas
df_query_geral.drop_duplicates(subset='NOME', keep='first', inplace=True)

df_query_geral_reduzido = df_query_geral[['NOME', 'CODIGO', 'EMB_TRANSF']]

df_analise_reduzido = df_analise_compra_por_estoque['NOME']

# Realizando o merge dos DataFrames
df_completo = pd.merge(df_analise_reduzido, df_query_geral_reduzido, on='NOME', how='left')

df_completo

                                          NOME  CODIGO  EMB_TRANSF
0               0800 FLEX SERVICOS DE TELECOMU    <NA>        <NA>
1                           CONTROLE DE PEDIDO   81569           1
2                                        FRETE   85065           1
3                                    GORJETA 1   85062           1
4                                    GORJETA 2   85063           1
...                                        ...     ...         ...
9437  TEMPERO KITANO TOQUE CHEF P/GREL 24X120G   17662          24
9438                   ZEZINHA GARBRECHT EBERT    <NA>        <NA>
9439             QUEIJO EBERT MINAS FRESCAL KG   73199           1
9440                     QUEIJO EBERT MINAS KG   73198           1
9441                               Total Geral    <NA>        <NA>

[9442 rows x 3 columns]

In [2]:
# Reordenando as colunas
df_merged = pd.merge(df_completo, din_tr, on='CODIGO', how='left')

df_merged = pd.merge(df_merged, din_vcto_medio, on='CODIGO', how='left')

# Supondo que 'df' é o seu DataFrame e 'VCTO_MEDIO' é a coluna equivalente a G5
# Aplicando a operação e tratando erros (assumindo que os erros seriam divisões por zero ou dados não numéricos)
df_merged['VAL EM MESES'] = df_merged['VAL_MÉDIA'].apply(lambda x: np.floor(x / 30) * 0.5 if pd.notnull(x) else np.nan)

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0
2,FRETE,85065,1,0,0,0,0,0,0.0
3,GORJETA 1,85062,1,0,0,0,0,0,0.0
4,GORJETA 2,85063,1,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN

In [3]:
df_merged = pd.merge(df_merged, df_query_geral[['CODIGO', 'SETOR', 'GRUPO', 'SUBGRUPO']], on='CODIGO', how='left')

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,GRUPO,SUBGRUPO
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,HIGIENE PESSOAL,SABONETE
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,HIGIENE PESSOAL,SABONETE
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,HIGIENE PESSOAL,SABONETE
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,HIGIENE PESSOAL,SABONETE
...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,TEMPEROS,TEMPEROS
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,QUEIJOS,FRESCAL
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,QUEIJOS,MINAS
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN

In [4]:
# Filtrando as colunas específicas de df_analise_compra_por_estoque
colunas_selecionadas = ['NOME', 'EST. ATUAL. SMJ', 'VDA MEDIA 30 D. SMJ', 'VDA 30D. SMJ', 'MAIOR VENDA SMJ', 
                        'est/vda * SMJ', 'PD. AB. SMJ', 'EST. ATUAL. STT', 'VDA MEDIA 30 D. STT', 'VDA 30D. STT', 
                        'MAIOR VENDA STT', 'est/vda * STT', 'PD. AB. STT']

df_analise_compra_por_estoque_filtrado = df_analise_compra_por_estoque[colunas_selecionadas]
df_analise_compra_por_estoque_filtrado = df_analise_compra_por_estoque_filtrado.drop_duplicates(subset='NOME', keep='first')

# Realizando o merge dos DataFrames com as colunas especificadas
df_merged = pd.merge(df_merged, df_analise_compra_por_estoque_filtrado, on='NOME', how='left')

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,VDA 30D. SMJ,MAIOR VENDA SMJ,est/vda * SMJ,PD. AB. SMJ,EST. ATUAL. STT,VDA MEDIA 30 D. STT,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,105.0,0.000,0.000000,0.000,0.000000,0.000000,67.0
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,-1.466667,0.0,0.000,0.000000,0.000,0.000000,-1.466667,0.0
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,0.0,0.000,0.000000,0.000,0.000000,0.000000,0.0
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,0.0,0.000,0.000000,0.000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,...,2.000,2.000000,19.924528,0.0,2.000,3.333333,2.000,3.333333,19.924528,24.0
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,...,3.072,4.075167,2.473028,10.0,NaN,NaN,NaN,NaN,NaN,NaN
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,...,17.292,17.292000,0.626070,10.0,NaN,NaN,NaN,NaN,NaN,NaN
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,103381.620,135836.114417,5.514729,103026.0,205042.392,154983.642333,162114.658,200569.118333,5.515967,50041.0

In [5]:
# Usando o método apply com uma função lambda para aplicar a lógica condicional
df_merged['EST SMJ > X VDA'] = df_merged.apply(
    lambda row: "SIM" if not pd.isna(row['EST. ATUAL. SMJ']) and not pd.isna(row['VDA 30D. SMJ']) and row['EST. ATUAL. SMJ'] > (row['VDA 30D. SMJ'] * 1) else ("NÃO" if not pd.isna(row['EST. ATUAL. SMJ']) and not pd.isna(row['VDA 30D. SMJ']) else np.nan),
    axis=1
)

# Usando o método apply com uma função lambda para aplicar a lógica condicional
df_merged['EST SMJ > X EMB.'] = df_merged.apply(
    lambda row: "SIM" if not pd.isna(row['EST. ATUAL. SMJ']) and not pd.isna(row['EMB_TRANSF']) and row['EST. ATUAL. SMJ'] > (row['EMB_TRANSF'] * 1.5) else ("NÃO" if not pd.isna(row['EST. ATUAL. SMJ']) and not pd.isna(row['EMB_TRANSF']) else np.nan),
    axis=1
)

# Usando o método apply com uma função lambda para aplicar a lógica condicional
df_merged['EST STT > X VDA'] = df_merged.apply(
    lambda row: "SIM" if not pd.isna(row['EST. ATUAL. STT']) and not pd.isna(row['MAIOR VENDA STT']) and row['EST. ATUAL. STT'] > (row['MAIOR VENDA STT'] * 2) else ("NÃO" if not pd.isna(row['EST. ATUAL. STT']) and not pd.isna(row['MAIOR VENDA STT']) else np.nan),
    axis=1
)

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,PD. AB. SMJ,EST. ATUAL. STT,VDA MEDIA 30 D. STT,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT,EST SMJ > X VDA,EST SMJ > X EMB.,EST STT > X VDA
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,105.0,0.000,0.000000,0.000,0.000000,0.000000,67.0,NÃO,NÃO,NÃO
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.0,0.000,0.000000,0.000,0.000000,-1.466667,0.0,NÃO,NÃO,NÃO
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.0,0.000,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.0,0.000,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,...,0.0,2.000,3.333333,2.000,3.333333,19.924528,24.0,SIM,SIM,NÃO
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,103026.0,205042.392,154983.642333,162114.658,200569.118333,5.515967,50041.0,SIM,NaN,NÃO

In [6]:
def custom_formula(row):
    try:
        if row['TR VIX'] == 1:
            if row['MAIOR VENDA SMJ'] == 0:
                result = np.floor(0.20 * row['EST. ATUAL. SMJ'] / row['EMB_TRANSF']) * row['EMB_TRANSF']
            else:
                temp_result = np.floor((row['EST. ATUAL. SMJ'] - (1.2 * row['MAIOR VENDA SMJ'])) / row['EMB_TRANSF']) * row['EMB_TRANSF']
                result = max(0, temp_result)
            return result * 0.50  # Multiplica por 0.5 se 'TR VIX' é 1
        else:
            if row['MAIOR VENDA SMJ'] == 0:
                result = np.floor(0.20 * row['EST. ATUAL. SMJ'] / row['EMB_TRANSF']) * row['EMB_TRANSF']
            else:
                temp_result = np.floor((row['EST. ATUAL. SMJ'] - (1.2 * row['MAIOR VENDA SMJ'])) / row['EMB_TRANSF']) * row['EMB_TRANSF']
                result = max(0, temp_result)
            return result  # Retorna o resultado sem multiplicar por 0.5
    except Exception as e:
        return np.nan  # Retorna NaN em caso de erro

df_merged['EXCEDENTE SMJ'] = df_merged.apply(custom_formula, axis=1)

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,EST. ATUAL. STT,VDA MEDIA 30 D. STT,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT,EST SMJ > X VDA,EST SMJ > X EMB.,EST STT > X VDA,EXCEDENTE SMJ
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000,0.000000,0.000000,67.0,NÃO,NÃO,NÃO,0.0
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000,0.000000,-1.466667,0.0,NÃO,NÃO,NÃO,0.0
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,...,2.000,3.333333,2.000,3.333333,19.924528,24.0,SIM,SIM,NÃO,24.0
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,205042.392,154983.642333,162114.658,200569.118333,5.515967,50041.0,SIM,NaN,NÃO,NaN

In [7]:
def custom_formula(row):
    try:
        # Verifica se EMB_TRANSF é 0 e retorna 'EXCEDENTE SMJ' se for o caso
        if row['MAIOR VENDA STT'] == 0:
            return row['EXCEDENTE SMJ']  # Corresponde ao Z1170 no Excel

        # Calcula o valor e garante que seja no mínimo 0
        valor_calculado = np.ceil(((row['MAIOR VENDA STT'] * min(row['VAL EM MESES'], 2)) - row['EST. ATUAL. STT']) / row['EMB_TRANSF']) * row['EMB_TRANSF']
        return max(valor_calculado, 0)
    except:
        return np.nan  # Retorna "" em caso de qualquer outro erro

# Aplicando a função ao DataFrame
df_merged.loc[:, 'NECESSIDADE STT'] = df_merged.apply(custom_formula, axis=1)
df_merged.loc[:, 'NECESSIDADE STT'] = df_merged['NECESSIDADE STT'].astype('float64')

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,VDA MEDIA 30 D. STT,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT,EST SMJ > X VDA,EST SMJ > X EMB.,EST STT > X VDA,EXCEDENTE SMJ,NECESSIDADE STT
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000000,0.000,0.000000,0.000000,67.0,NÃO,NÃO,NÃO,0.0,0.0
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000000,0.000,0.000000,-1.466667,0.0,NÃO,NÃO,NÃO,0.0,0.0
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0,0.0
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000000,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,...,3.333333,2.000,3.333333,19.924528,24.0,SIM,SIM,NÃO,24.0,24.0
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0,NaN
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0,NaN
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,154983.642333,162114.658,200569.118333,5.515967,50041.0,SIM,NaN,NÃO,NaN,NaN

In [8]:
# Realizando as conversões
df_merged.loc[:, 'NECESSIDADE STT'] = pd.to_numeric(df_merged['NECESSIDADE STT'], errors='coerce')
df_merged.loc[:, 'EXCEDENTE SMJ'] = pd.to_numeric(df_merged['EXCEDENTE SMJ'], errors='coerce')

# Aplicando a função
df_merged.loc[:, 'PEDIDO'] = df_merged.apply(lambda row: row['EXCEDENTE SMJ'] if row['NECESSIDADE STT'] > row['EXCEDENTE SMJ'] else row['NECESSIDADE STT'], axis=1)

df_merged

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT,EST SMJ > X VDA,EST SMJ > X EMB.,EST STT > X VDA,EXCEDENTE SMJ,NECESSIDADE STT,PEDIDO
0,0800 FLEX SERVICOS DE TELECOMU,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONTROLE DE PEDIDO,81569,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,67.0,NÃO,NÃO,NÃO,0.0,0.0,0.0
2,FRETE,85065,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,-1.466667,0.0,NÃO,NÃO,NÃO,0.0,0.0,0.0
3,GORJETA 1,85062,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0,0.0,0.0
4,GORJETA 2,85063,1,0,0,0,0,0,0.0,HIGIENE E BELEZA,...,0.000,0.000000,0.000000,0.0,NÃO,NÃO,NÃO,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9437,TEMPERO KITANO TOQUE CHEF P/GREL 24X120G,17662,24,0,0,0,0,472,7.5,MERCEARIA,...,2.000,3.333333,19.924528,24.0,SIM,SIM,NÃO,24.0,24.0,24.0
9438,ZEZINHA GARBRECHT EBERT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,QUEIJO EBERT MINAS FRESCAL KG,73199,1,0,0,0,0,13,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0,NaN,NaN
9440,QUEIJO EBERT MINAS KG,73198,1,0,0,0,0,18,0.0,FRIOS E LATICÍNIOS,...,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,0.0,NaN,NaN
9441,Total Geral,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,...,162114.658,200569.118333,5.515967,50041.0,SIM,NaN,NÃO,NaN,NaN,NaN

In [9]:
# Aplicando os filtros
df_filtrado = df_merged[
    (df_merged["TR SMJ"] == 0) &
    (df_merged["TR STT"] == 1) &
    (df_merged['EST SMJ > X VDA'] == 'SIM') &
    (df_merged['EST SMJ > X EMB.'] == 'SIM') &
    (df_merged['EST STT > X VDA'] == 'NÃO') &
    (df_merged['EXCEDENTE SMJ'] > 0) &
    (df_merged['NECESSIDADE STT'] > 0) &
    (df_merged['PEDIDO'] > 0)
]

df_final = df_filtrado.copy()
df_final['PEDIDO'] = df_final['PEDIDO'].fillna(0).astype('int64')

df_final

,NOME,CODIGO,EMB_TRANSF,TR MCP,TR SMJ,TR STT,TR VIX,VAL_MÉDIA,VAL EM MESES,SETOR,...,VDA 30D. STT,MAIOR VENDA STT,est/vda * STT,PD. AB. STT,EST SMJ > X VDA,EST SMJ > X EMB.,EST STT > X VDA,EXCEDENTE SMJ,NECESSIDADE STT,PEDIDO
97,MAIONESE D AJUDA BISNAGA 6X175GR,34347,12,0,0,1,0,243,4.0,MERCEARIA,...,2.0,4.083333,4.432432,0.0,SIM,SIM,NÃO,12.0,12.0,12
102,MOLHO TOM DAJUDA PENEIRADO SUP SACHE 24X200GR,55914,24,0,0,1,0,299,4.5,MERCEARIA,...,2.0,6.916667,6.935780,0.0,SIM,SIM,NÃO,24.0,24.0,24
337,ENERGETICO RED BULL BR CAN 473ML,47375,12,0,0,1,1,529,8.5,BEBIDAS,...,8.0,14.250000,1.765363,0.0,SIM,SIM,NÃO,12.0,12.0,12
339,ENERGETICO RED BULL COCO EDITION 24X250ML,69125,24,0,0,1,1,256,4.0,BEBIDAS,...,16.0,16.000000,3.477273,0.0,SIM,SIM,NÃO,36.0,24.0,24
340,ENERGETICO RED BULL ENERGY DRINK 250ML,10162,24,0,0,1,1,620,10.0,BEBIDAS,...,171.0,171.000000,1.509202,0.0,SIM,SIM,NÃO,156.0,360.0,156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9023,ACUCAR CRISTAL SANTA ISABEL 10X2KG,10035,10,0,0,1,1,728,12.0,MERCEARIA,...,271.0,271.000000,1.667992,0.0,SIM,SIM,NÃO,35.0,70.0,35
9024,ACUCAR CRISTAL SANTA ISABEL 6X5KG,10036,6,0,0,1,1,721,12.0,MERCEARIA,...,262.0,513.166667,1.789464,0.0,SIM,SIM,NÃO,66.0,24.0,24
9025,ACUCAR DEMERARA SANTA ISABEL 10X1KG,84579,10,0,0,1,1,662,11.0,MERCEARIA,...,57.0,57.000000,2.012346,0.0,SIM,SIM,NÃO,10.0,20.0,10
9251,BISCOITO VILMA CREAM CRACKER INTEGRAL 20X360G,69034,20,0,0,1,0,254,4.0,MERCEARIA,...,57.0,57.000000,2.236111,0.0,SIM,SIM,NÃO,20.0,40.0,20
9253,BISCOITO VILMA RECH CHOCOLATE 30X120GR,68327,30,0,0,1,0,244,4.0,MERCEARIA,...,181.0,181.000000,2.033033,0.0,SIM,SIM,NÃO,90.0,30.0,30

In [10]:
df_csv = df_final[['CODIGO', 'PEDIDO']]
df_csv

      CODIGO  PEDIDO
97     34347      12
102    55914      24
337    47375      12
339    69125      24
340    10162     156
...      ...     ...
9023   10035      35
9024   10036      24
9025   84579      10
9251   69034      20
9253   68327      30

[362 rows x 2 columns]