In [8]:
import os
import pandas as pd
import sqlite3

# Configurações para exibição
pd.set_option('display.max_rows', None)  # Substitua None por um número específico se quiser limitar a um número específico de linhas
pd.set_option('display.max_columns', None)  # Substitua None por um número específico se quiser limitar a um número específico de colunas
pd.set_option('display.width', None)  # Ajuste a largura para acomodar a exibição das colunas
pd.set_option('display.max_colwidth', None)  # Ajuste para ver o conteúdo completo das células

class BancoDeDados:
    def __init__(self, db_path='dados_cad.db'):
        self.db_path = os.path.join(os.getcwd(), db_path.replace('\\','/')) # Ajusta o caminho para ser independente do SO

    # O resto da sua classe permanece igual...

    def ler_tabela(self, nome_tabela):
        """
        Lê e exibe os dados de uma tabela específica usando pandas.
        """
        conexao = sqlite3.connect(self.db_path)
        try:
            df = pd.read_sql_query(f"SELECT * FROM {nome_tabela}", conexao)
            print(f"Dados da tabela {nome_tabela}:")
            display(df)
        except Exception as e:
            print(f"Erro ao ler a tabela {nome_tabela}: {e}")
        finally:
            conexao.close()

# Exemplo de uso:
db = BancoDeDados()

# Para ler e exibir os dados da tabela cadastro_temporario
#db.ler_tabela("cadastro_temporario")

# Para ler e exibir os dados da tabela cadastro_definitivo
db.ler_tabela("cadastro_definitivo")

Dados da tabela cadastro_definitivo:

,ID,MOTIVO_CADASTRO,EAN,DESCRICAO_COMPLETA,DESCRICAO_CONSUMIDOR,FORNECEDOR,MARCA,GRAMATURA,EMBALAGEM_COMPRA,NCM,CODIGO_INTERNO,SETOR,GRUPO,SUBGRUPO,CATEGORIA,PRIORIDADE,MIX SMJ,MIX STT,MIX VIX,MIX MCP,TR SMJ,TR STT,TR VIX,TR MCP,AP
0,1,FSDFSD,4,FSFDS,FSDFDSF,SDFFDS,SDF,SDFDSF,5,4,SDFSDFDS,FSDF,SDFSDFSD,FSDF,SDFDS,,,SIM,,,,,,,SIM
1,2,FSDFSD,4,FSFDS,FSDFDSF,SDFFDS,SDF,SDFDSF,5,4,SDFSDFDS,FSDF,SDFSDFSD,FSDF,SDFDS,,,SIM,,,,,,,SIM
2,3,FSDFSD,4,FSFDS,FSDFDSF,SDFFDS,SDF,SDFDSF,5,4,SDFSDFDS,FSDF,SDFSDFSD,FSDF,SDFDS,SIM,,SIM,,,,,,,SIM